[general]
import = [ "themes/campbell.toml" ]

[window]
dimensions = { columns = 180, lines = 52 }
option_as_alt = "Both" # (macOS only)

[terminal]
osc52 = "CopyPaste"

[font]
normal = { family = "Maple Mono NL NF CN", style = "Regular" }
bold = { family = "Maple Mono NL NF CN", style = "Bold" }
italic = { family = "Maple Mono NL NF CN", style = "Italic" }
bold_italic = { family = "Maple Mono NL NF CN", style = "Bold Italic" }
size = 12
offset = { x = 0, y = 2 }

[scrolling]
history = 10000

